name: Feature / Improvement
description: Turn words into code by filling this friendly spec.
title: "[Feature]: "
labels: ["spec","ready-for-CI"]
body:
  - type: input
    id: purpose
    attributes:
      label: Purpose (why)
      placeholder: What pain or possibility does this address?
    validations:
      required: true
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: As a <who>, I want <what>, so that <why>.
      placeholder: As a camper, I want a map pin so that I can join easily.
    validations:
      required: true
  - type: textarea
    id: inputs
    attributes:
      label: Inputs
      placeholder: Buttons, fields, events, data coming in.
  - type: textarea
    id: outputs
    attributes:
      label: Outputs
      placeholder: UI changes, saved files, logs, API responses.
  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria (check all when done)
      options:
        - label: I can perform the main action and see the expected result.
        - label: Error states show clear, human messages.
        - label: Works in Brave with shields up (if UI).
  - type: textarea
    id: non_goals
    attributes:
      label: Non-Goals
      placeholder: What we will not do in this iteration.
  - type: textarea
    id: notes
    attributes:
      label: Notes / Examples
      placeholder: Links, sketches, example text/UI states.
